/*
 @title XTag Manager: AT Internet SmartTag Adapter
 @author DENIS ROUSSEAU
 @version 8.2.0
*/
var stat_stag={tag:null,init:function(a,d,c,e){stat_stag.initCookie(d);stat_stag.tag?e||stat_stag.tag.setContext("page",{}):"object"===typeof STAT_Method?(d=(window.xtsd?xtsd+stat_stag.collectDomain():"").split("//"),d=1<d.length?d[1]:d[0],a={site:xtsite,secure:"boolean"===typeof a?a:"https:"===document.location.protocol,cookieDomain:c||stat_stag.cookieDomain(),collectDomain:d,collectDomainSSL:d},stat_stag.tag=new ATInternet.Tracker.Tag(a)):stat_stag.tag=new ATInternet.Tracker.Tag},initCheck:function(){stat_stag.init(null,
null,null,!0)},initCookie:function(a){"boolean"===typeof a&&(a?ATInternet.Utils.userOptedIn():ATInternet.Utils.userOptedOut())},cookieDomain:function(){var a=window.location.hostname.split(".");return"."+a.slice(-(2===a[a.length-1].length?3:2)).join(".")},collectDomain:function(){var a=0;return window.xtsd&&0<xtsd.indexOf(".")?"":!window.xtsd||0<=(a=xtsd.indexOf("log"))&&"w"!==xtsd.charAt(a+3)?".xiti.com":".ati-host.net"},setParams:function(){if(stat_stag.tag){"function"===typeof window.xt_cart&&
xt_cart();for(var a=0,d=window.xtparam?xtparam.split("&"):[],c=[],e="",f=null,g=null,l=null,h=null,j=null,m=null,n=null,b=null,k=!window.xttp||"conf1"!==window.xttp,a=0;a<d.length;a++)switch(c=d[a].split("="),c[0]){case "an":j=j||{};j.id=parseInt(c[1],10);break;case "at":j=j||{};j.id=c[1];break;case "ac":j=j||{};j.category=c[1];break;case "mc":m=m||{};m.keyword=c[1];break;case "np":m=m||{};m.resultPageNumber=c[1];break;case "tp":n=n||{};n.isBasketPage="cart"===c[1]||"pre1"===c[1];break;case "idcart":n=
n||{};n.cartId=c[1];break;case "cmd":b=b||{};b.orderId=c[1];break;case "newcus":b=b||{};b.newCustomer=c[1];break;case "roimt":if(k||1*c[1])b=b||{},b.turnover=c[1];break;case "mp":b=b||{};b.paymentMethod=c[1];break;case "st":b=b||{};b.status=c[1];break;case "mtht":if(k||1*c[1])b=b||{},b.amount=b.amount||{},b.amount.amountTaxFree=c[1];break;case "mtttc":if(k||1*c[1])b=b||{},b.amount=b.amount||{},b.amount.amountTaxIncluded=c[1];break;case "tax":if(k||1*c[1])b=b||{},b.amount=b.amount||{},b.amount.taxAmount=
c[1];break;case "fpht":if(k||1*c[1])b=b||{},b.delivery=b.delivery||{},b.delivery.shippingFeesTaxFree=c[1];break;case "fp":if(k||1*c[1])b=b||{},b.delivery=b.delivery||{},b.delivery.shippingFeesTaxIncluded=c[1];break;case "dl":b=b||{};b.delivery=b.delivery||{};b.delivery.deliveryMethod=c[1];break;case "pcd":b=b||{};b.discount=b.discount||{};b.discount.promotionalCode=c[1];break;case "dscht":if(k||1*c[1])b=b||{},b.discount=b.discount||{},b.discount.discountTaxFree=c[1];break;case "dsc":if(k||1*c[1])b=
b||{},b.discount=b.discount||{},b.discount.discountTaxIncluded=c[1];break;default:if(c[0]&&(e=c[0].charAt(0),f=c[0].replace(e,""),!isNaN(f)))switch(e){case "x":g=g||{};g[f]=c[1];break;case "f":l=l||{},l[f]=c[1]}}g&&(h=h||{},h.site=g);l&&(h=h||{},h.page=l);h&&stat_stag.tag.customVars&&stat_stag.tag.customVars.set(h);j&&stat_stag.tag.identifiedVisitor&&stat_stag.tag.identifiedVisitor.set(j);m&&(m.keyword&&stat_stag.tag.internalSearch)&&stat_stag.tag.internalSearch.set(m);n&&stat_stag.tag.cart&&stat_stag.tag.cart.set(n);
b&&stat_stag.tag.order&&(k&&"pre1"===window.xttp&&(b.confirmationRequired=!0),stat_stag.tag.order.set(b),k||stat_stag.tag.setParam("tp","conf1"))}},jsonName:function(a){a=a.split("::");var d={},c=0;d.name=0<a.length?a.pop():"";for(c=0;c<a.length;c++)d["chapter"+(c+1).toString()]=a[c];window.xtn2&&(d.level2=xtn2);return d},clickType:function(a){return"T"===a?"download":"S"===a?"exit":"N"===a?"navigation":"action"},sendPage:function(){stat_stag.initCheck();stat_stag.tag.page&&(stat_stag.tag.page.set(stat_stag.jsonName(xtpage)),
stat_stag.setParams(),stat_stag.tag.dispatch())},sendClick:function(a,d,c){stat_stag.initCheck();var e=stat_stag.jsonName(a),f=null;switch(d){case "F":stat_stag.tag.page&&stat_stag.tag.page.send(e);break;case "IS":stat_stag.tag.internalSearch&&(f=getUrlParser(a))&&(f.mc&&!isNaN(f.np)&&!isNaN(f.mcrg))&&stat_stag.tag.internalSearch.send({elem:c,keyword:f.mc,resultPageNumber:f.np,resultPosition:f.mcrg});break;default:stat_stag.tag.click&&(e.type=stat_stag.clickType(d),e.elem=c,stat_stag.tag.click.send(e))}},
sendVideo:function(a,d,c,e,f,g,l,h,j,m,n,b,k,q,p){stat_stag.initCheck();stat_stag.tag.richMedia&&(a=parseInt(a.split("=")[1],10),g=c.split("::"),c=e.split("&")[0],f=1<g.length?g[1]:g[0],g=1<g.length?g[0]:"",p=p?p.target:{},h=null,p.added||(stat_stag.tag.richMedia.add({mediaType:"video",playerId:a,mediaLevel2:d,mediaLabel:f,mediaTheme1:g,isEmbedded:!0,webdomain:p.a&&p.a.src?p.a.src.split("?")[0]:"",broadcastMode:b,duration:l,refreshDuration:{"0":5,1:15,5:30,10:60}}),p.added=!0),h={action:c,playerId:a,
mediaLabel:f,mediaTheme1:g},"info"===c&&(h.isBuffering=0<=e.indexOf("buf=1")),stat_stag.tag.richMedia.send(h))},stopVideo:function(){stat_stag.tag&&stat_stag.tag.richMedia&&stat_stag.tag.richMedia.removeAll()},productView:function(a,d,c,e){stat_stag.tag&&(stat_stag.tag.product&&a)&&(a={productId:a+(d?"["+d+"]":"")},c&&!isNaN(c)&&(a.category1=c+(e?"["+e+"]":"")),stat_stag.tag.product.add(a))},addProduct:function(a){stat_stag.tag&&(stat_stag.tag.cart&&a&&a.ID)&&stat_stag.tag.cart.add({product:{productId:a.ID+
(a.Description?"["+decodeURIComponent(a.Description)+"]":""),category1:a.Category||"",unitPriceTaxFree:a.UnitPriceTF||"0",unitPriceTaxIncluded:a.UnitPriceTI||"0",discountTaxIncluded:a.DiscountTI,discountTaxFree:a.DiscountTF,quantity:a.Quantity||"1"}})}};
(function(){window.xt_med=function(a,d,c,e){stat_stag.initCheck();stat_stag.tag.click&&"C"===a&&(a=stat_stag.jsonName(c),a.type=stat_stag.clickType(e),a.level2=d,stat_stag.tag.click.send(a))};window.xt_click=function(a,d,c,e,f,g,l,h){stat_stag.initCheck();stat_stag.tag.click&&(e=stat_stag.jsonName(e),e.level2=c,h&&(e.customObject=h),"F"===d?stat_stag.tag.page.send(e):"C"===d&&(e.type=stat_stag.clickType(f),e.elem=a&&("A"===a.tagName||"FORM"===a.tagName)?a:null,stat_stag.tag.click.send(e)));return!0};
window.xt_form=function(a,d,c,e,f,g,l){xt_click(a,d,c,e,f,null,null,l);return g&&a.submit?(setTimeout(function(){a.submit()},500),!1):!0};window.xt_addProduct_load=function(a,d){stat_stag.initCheck();d&&(stat_stag.tag&&stat_stag.tag.product)&&stat_stag.tag.product.add({category1:a,productId:d})};window.xt_rm=function(a,d,c,e,f,g,l,h,j,m,n,b,k,q){stat_stag.sendVideo(a,d,c,e,f,g,l,h,j,m,n,b,k,q)}})();(function(){stat_stag.init();stat_stag.sendPage()})();
